import type {
  AgentDecision,
  Campaign,
  ChannelTrendPoint,
  CreativeAsset,
} from "./types";

// Mock database — stands in for Google Ads API / Meta Marketing API / Lending CRM.

export const initialCampaigns: Campaign[] = [
  {
    id: "cmp_g_search_01",
    name: "US Personal Loan — Exact Match",
    channel: "Google",
    placement: "Google Search",
    status: "ACTIVE",
    dailyBudget: 5200,
    spentToday: 3810,
    impressions: 412_540,
    clicks: 9840,
    leads: 612,
    approvedLoans: 214,
    disbursedAmount: 1_284_000,
    cpl: 6.22,
    cps: 17.8,
    compliancePassRate: 0.98,
    last20ApprovalRate: 0.35,
    aiSuggestion: "扩量 +15%：授信通过率 35% 高于阈值 22%",
  },
  {
    id: "cmp_g_pmax_02",
    name: "PMax — Debt Consolidation Q3",
    channel: "Google",
    placement: "Google Performance Max",
    status: "LEARNING",
    dailyBudget: 3000,
    spentToday: 2140,
    impressions: 780_210,
    clicks: 12_410,
    leads: 498,
    approvedLoans: 118,
    disbursedAmount: 702_000,
    cpl: 4.3,
    cps: 18.1,
    compliancePassRate: 0.94,
    last20ApprovalRate: 0.24,
    aiSuggestion: "保持观察：学习期剩余 2 天",
  },
  {
    id: "cmp_m_feed_03",
    name: "Meta Feed — Fast Cash Lookalike 3%",
    channel: "Meta",
    placement: "Meta Feed",
    status: "ACTIVE",
    dailyBudget: 2400,
    spentToday: 2280,
    impressions: 1_204_880,
    clicks: 21_400,
    leads: 1042,
    approvedLoans: 96,
    disbursedAmount: 388_000,
    cpl: 2.19,
    cps: 23.75,
    compliancePassRate: 0.86,
    last20ApprovalRate: 0.09,
    aiSuggestion: "风控预警：近 20 条线索授信通过率 9% < 10%",
  },
  {
    id: "cmp_m_reels_04",
    name: "Meta Reels — Creator UGC Loan Stories",
    channel: "Meta",
    placement: "Meta Reels",
    status: "COMPLIANCE_HOLD",
    dailyBudget: 1600,
    spentToday: 640,
    impressions: 512_300,
    clicks: 14_980,
    leads: 388,
    approvedLoans: 41,
    disbursedAmount: 141_500,
    cpl: 1.65,
    cps: 15.6,
    compliancePassRate: 0.61,
    last20ApprovalRate: 0.16,
    aiSuggestion: "合规拦截：素材缺少 APR 与还款期限披露",
  },
];

export const initialDecisions: AgentDecision[] = [
  {
    id: "dec_1042",
    timestamp: "2026-07-25T09:42:00Z",
    agentType: "Planner",
    actionType: "BUDGET_SHIFT",
    targetChannel: "Google",
    campaignId: "cmp_g_search_01",
    campaignName: "US Personal Loan — Exact Match",
    confidenceScore: 0.91,
    reasoningChain: [
      "拉取近 24h 数据：Meta Feed 线索 1,042 条，CPL $2.19（前端表现最优）。",
      "对齐借贷 CRM 后端数据：Meta Feed 授信通过率 9.2%，Google Search 授信通过率 35.0%（差值 25.8pt）。",
      "折算真实成本：Meta Feed CPS $23.75 vs Google Search CPS $17.80，Google 每笔放款便宜 25.1%。",
      "Google Search 今日预算消耗 73%，尚有 impression share lost (budget) 18%，具备承接空间。",
      "决策：从 Meta Feed 转移 $1,000 日预算至 Google Search，预计降低整体 CPS 约 6.4%。",
    ],
    dataMetricsTrigger: {
      metric: "ApprovalRate",
      currentValue: 0.092,
      thresholdValue: 0.22,
    },
    status: "EXECUTED",
    effect: "Meta Feed −$1,000 → Google Search +$1,000",
    rollbackTo: "Meta Feed $3,400 / Google Search $4,200",
  },
  {
    id: "dec_1041",
    timestamp: "2026-07-25T09:15:00Z",
    agentType: "Compliance",
    actionType: "COMPLIANCE_REJECT",
    targetChannel: "Meta",
    campaignId: "cmp_m_reels_04",
    campaignName: "Meta Reels — Creator UGC Loan Stories",
    confidenceScore: 0.99,
    reasoningChain: [
      "扫描新素材 crv_reels_88：正文包含 “Instant approval without income proof”。",
      "命中 Fintech 禁词库（无条件批准类表述）与 Google Personal Loans Policy 误导性宣传条款。",
      "素材未声明最长还款期限（Google 要求 ≥ 61 天），未披露最高 APR。",
      "Meta 侧未勾选 Financial Products and Services 特殊广告类别，存在封号风险。",
      "决策：阻断提交，广告系列置为 COMPLIANCE_HOLD，推送 Auto-Fix 建议。",
    ],
    dataMetricsTrigger: {
      metric: "CPL",
      currentValue: 1.65,
      thresholdValue: 6.0,
    },
    status: "EXECUTED",
    effect: "素材拦截 + 广告系列 COMPLIANCE_HOLD",
    rollbackTo: "Meta Reels ACTIVE",
  },
  {
    id: "dec_1040",
    timestamp: "2026-07-25T08:50:00Z",
    agentType: "Execution",
    actionType: "BID_ADJUST",
    targetChannel: "Google",
    campaignId: "cmp_g_pmax_02",
    campaignName: "PMax — Debt Consolidation Q3",
    confidenceScore: 0.76,
    reasoningChain: [
      "PMax 处于学习期，tCPA $42 下放款量偏低（118 笔 / 498 线索）。",
      "后端 30 天 ROAS 2.4x，高于盈亏平衡线 1.8x。",
      "决策：tCPA 上调 8%（$42 → $45.4），扩大高质量流量覆盖。",
    ],
    dataMetricsTrigger: {
      metric: "ROAS",
      currentValue: 2.4,
      thresholdValue: 1.8,
    },
    status: "EXECUTED",
    effect: "tCPA $42.00 → $45.36",
    rollbackTo: "tCPA $42.00",
  },
  {
    id: "dec_1039",
    timestamp: "2026-07-25T08:20:00Z",
    agentType: "Planner",
    actionType: "BUDGET_SHIFT",
    targetChannel: "Meta",
    campaignId: "cmp_m_feed_03",
    campaignName: "Meta Feed — Fast Cash Lookalike 3%",
    confidenceScore: 0.68,
    reasoningChain: [
      "Meta Feed 近 20 条线索授信通过率 9%，低于风控优先模式阈值 10%。",
      "计划削减该广告系列日预算 42%（$2,400 → $1,400），幅度 > 30%。",
      "变更幅度超过自动执行阈值，转入 Human-in-the-Loop 审批队列。",
    ],
    dataMetricsTrigger: {
      metric: "CostPerDisbursement",
      currentValue: 23.75,
      thresholdValue: 19.0,
    },
    status: "PENDING_APPROVAL",
    effect: "Meta Feed 日预算 $2,400 → $1,400（−42%）",
    rollbackTo: "Meta Feed $2,400",
  },
  {
    id: "dec_1038",
    timestamp: "2026-07-25T07:55:00Z",
    agentType: "Creative",
    actionType: "CREATIVE_PAUSE",
    targetChannel: "Meta",
    campaignId: "cmp_m_feed_03",
    campaignName: "Meta Feed — Fast Cash Lookalike 3%",
    confidenceScore: 0.84,
    reasoningChain: [
      "素材 crv_feed_12 疲劳度指标：frequency 4.8，CTR 7 日下降 38%。",
      "该素材线索授信通过率 6.1%，显著低于账户均值 18.4%。",
      "决策：暂停该素材，启用合规版变体 crv_feed_19（含 APR 披露）。",
    ],
    dataMetricsTrigger: {
      metric: "ApprovalRate",
      currentValue: 0.061,
      thresholdValue: 0.15,
    },
    status: "PENDING_APPROVAL",
    effect: "暂停 crv_feed_12 → 启用 crv_feed_19",
    rollbackTo: "crv_feed_12 ACTIVE",
  },
];

export const initialCreatives: CreativeAsset[] = [
  {
    id: "crv_g_01",
    headline: "Personal Loans up to $25,000 — Fixed Rates",
    bodyText:
      "Check your rate in 2 minutes. Representative APR 12.9%–35.9%. Repayment terms from 12 to 60 months. Approval subject to credit and affordability checks.",
    loanTermRange: "12 months - 60 months",
    maxApr: 35.9,
    complianceStatus: "PASSED",
    complianceLogs: ["Google Personal Loans Policy: 期限与 APR 披露完整。"],
  },
  {
    id: "crv_m_02",
    headline: "Need cash before payday?",
    bodyText:
      "Apply online and get a decision fast. Terms 61 days to 36 months. Max APR 34.9%.",
    loanTermRange: "61 days - 36 months",
    maxApr: 34.9,
    complianceStatus: "WARNING",
    complianceLogs: ["Meta: 需勾选 Financial Products and Services 特殊广告类别。"],
  },
  {
    id: "crv_reels_88",
    headline: "100% Approval — No Credit Check!",
    bodyText:
      "Instant approval without income proof. Get money in your account today, guaranteed.",
    loanTermRange: "—",
    maxApr: 0,
    complianceStatus: "FAILED",
    complianceLogs: [
      "命中禁词：100% Approval / No Credit Check / Instant approval without income proof。",
      "缺少还款期限（≥ 61 天）与最高 APR 披露。",
    ],
  },
];

export const funnel = [
  { stage: "Impressions", value: 2_909_930, note: "四渠道聚合曝光" },
  { stage: "Clicks", value: 58_630, note: "CTR 2.01%" },
  { stage: "Form Leads", value: 2540, note: "CPL $3.71" },
  { stage: "Credit Approved", value: 469, note: "授信通过率 18.5%" },
  { stage: "Loan Disbursed", value: 312, note: "CPS $19.02" },
];

export const channelTrend: ChannelTrendPoint[] = [
  { day: "07-19", googleFrontEndRoi: 3.1, metaFrontEndRoi: 4.4, googleTrueRoas: 2.2, metaTrueRoas: 1.3 },
  { day: "07-20", googleFrontEndRoi: 3.2, metaFrontEndRoi: 4.6, googleTrueRoas: 2.3, metaTrueRoas: 1.25 },
  { day: "07-21", googleFrontEndRoi: 3.0, metaFrontEndRoi: 4.9, googleTrueRoas: 2.35, metaTrueRoas: 1.1 },
  { day: "07-22", googleFrontEndRoi: 3.4, metaFrontEndRoi: 5.1, googleTrueRoas: 2.5, metaTrueRoas: 1.05 },
  { day: "07-23", googleFrontEndRoi: 3.5, metaFrontEndRoi: 5.3, googleTrueRoas: 2.6, metaTrueRoas: 0.98 },
  { day: "07-24", googleFrontEndRoi: 3.6, metaFrontEndRoi: 5.0, googleTrueRoas: 2.72, metaTrueRoas: 0.95 },
  { day: "07-25", googleFrontEndRoi: 3.8, metaFrontEndRoi: 4.8, googleTrueRoas: 2.86, metaTrueRoas: 0.92 },
];

export const channelBreakdown = [
  { channel: "Google Search", spend: 3810, disbursed: 1_284_000, cps: 17.8, approval: 0.35 },
  { channel: "Google PMax", spend: 2140, disbursed: 702_000, cps: 18.1, approval: 0.24 },
  { channel: "Meta Feed", spend: 2280, disbursed: 388_000, cps: 23.75, approval: 0.09 },
  { channel: "Meta Reels", spend: 640, disbursed: 141_500, cps: 15.6, approval: 0.16 },
];
