/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LpRouteImport } from './routes/lp'
import { Route as CreativeRouteImport } from './routes/creative'
import { Route as ConversionsRouteImport } from './routes/conversions'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateCreativeImageRouteImport } from './routes/api/generate-creative-image'
import { Route as ApiPublicLoanEventsRouteImport } from './routes/api/public/loan-events'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as ApiPublicCronUploadConversionsRouteImport } from './routes/api/public/cron/upload-conversions'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LpRoute = LpRouteImport.update({
  id: '/lp',
  path: '/lp',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativeRoute = CreativeRouteImport.update({
  id: '/creative',
  path: '/creative',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversionsRoute = ConversionsRouteImport.update({
  id: '/conversions',
  path: '/conversions',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateCreativeImageRoute =
  ApiGenerateCreativeImageRouteImport.update({
    id: '/api/generate-creative-image',
    path: '/api/generate-creative-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLoanEventsRoute = ApiPublicLoanEventsRouteImport.update({
  id: '/api/public/loan-events',
  path: '/api/public/loan-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronUploadConversionsRoute =
  ApiPublicCronUploadConversionsRouteImport.update({
    id: '/api/public/cron/upload-conversions',
    path: '/api/public/cron/upload-conversions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/conversions': typeof ConversionsRoute
  '/creative': typeof CreativeRoute
  '/lp': typeof LpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-creative-image': typeof ApiGenerateCreativeImageRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/loan-events': typeof ApiPublicLoanEventsRoute
  '/api/public/cron/upload-conversions': typeof ApiPublicCronUploadConversionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/conversions': typeof ConversionsRoute
  '/creative': typeof CreativeRoute
  '/lp': typeof LpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-creative-image': typeof ApiGenerateCreativeImageRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/loan-events': typeof ApiPublicLoanEventsRoute
  '/api/public/cron/upload-conversions': typeof ApiPublicCronUploadConversionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/conversions': typeof ConversionsRoute
  '/creative': typeof CreativeRoute
  '/lp': typeof LpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-creative-image': typeof ApiGenerateCreativeImageRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/loan-events': typeof ApiPublicLoanEventsRoute
  '/api/public/cron/upload-conversions': typeof ApiPublicCronUploadConversionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/campaigns'
    | '/conversions'
    | '/creative'
    | '/lp'
    | '/sitemap.xml'
    | '/api/generate-creative-image'
    | '/api/public/leads'
    | '/api/public/loan-events'
    | '/api/public/cron/upload-conversions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/campaigns'
    | '/conversions'
    | '/creative'
    | '/lp'
    | '/sitemap.xml'
    | '/api/generate-creative-image'
    | '/api/public/leads'
    | '/api/public/loan-events'
    | '/api/public/cron/upload-conversions'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/campaigns'
    | '/conversions'
    | '/creative'
    | '/lp'
    | '/sitemap.xml'
    | '/api/generate-creative-image'
    | '/api/public/leads'
    | '/api/public/loan-events'
    | '/api/public/cron/upload-conversions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CampaignsRoute: typeof CampaignsRoute
  ConversionsRoute: typeof ConversionsRoute
  CreativeRoute: typeof CreativeRoute
  LpRoute: typeof LpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiGenerateCreativeImageRoute: typeof ApiGenerateCreativeImageRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
  ApiPublicLoanEventsRoute: typeof ApiPublicLoanEventsRoute
  ApiPublicCronUploadConversionsRoute: typeof ApiPublicCronUploadConversionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp': {
      id: '/lp'
      path: '/lp'
      fullPath: '/lp'
      preLoaderRoute: typeof LpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative': {
      id: '/creative'
      path: '/creative'
      fullPath: '/creative'
      preLoaderRoute: typeof CreativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversions': {
      id: '/conversions'
      path: '/conversions'
      fullPath: '/conversions'
      preLoaderRoute: typeof ConversionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-creative-image': {
      id: '/api/generate-creative-image'
      path: '/api/generate-creative-image'
      fullPath: '/api/generate-creative-image'
      preLoaderRoute: typeof ApiGenerateCreativeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/loan-events': {
      id: '/api/public/loan-events'
      path: '/api/public/loan-events'
      fullPath: '/api/public/loan-events'
      preLoaderRoute: typeof ApiPublicLoanEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/upload-conversions': {
      id: '/api/public/cron/upload-conversions'
      path: '/api/public/cron/upload-conversions'
      fullPath: '/api/public/cron/upload-conversions'
      preLoaderRoute: typeof ApiPublicCronUploadConversionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CampaignsRoute: CampaignsRoute,
  ConversionsRoute: ConversionsRoute,
  CreativeRoute: CreativeRoute,
  LpRoute: LpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiGenerateCreativeImageRoute: ApiGenerateCreativeImageRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
  ApiPublicLoanEventsRoute: ApiPublicLoanEventsRoute,
  ApiPublicCronUploadConversionsRoute: ApiPublicCronUploadConversionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
