/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CreativeLabRouteImport } from './routes/creative-lab'
import { Route as CreativeRouteImport } from './routes/creative'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateCreativeImageRouteImport } from './routes/api/generate-creative-image'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativeLabRoute = CreativeLabRouteImport.update({
  id: '/creative-lab',
  path: '/creative-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativeRoute = CreativeRouteImport.update({
  id: '/creative',
  path: '/creative',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateCreativeImageRoute =
  ApiGenerateCreativeImageRouteImport.update({
    id: '/api/generate-creative-image',
    path: '/api/generate-creative-image',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/compliance': typeof ComplianceRoute
  '/creative': typeof CreativeRoute
  '/creative-lab': typeof CreativeLabRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-creative-image': typeof ApiGenerateCreativeImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/compliance': typeof ComplianceRoute
  '/creative': typeof CreativeRoute
  '/creative-lab': typeof CreativeLabRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-creative-image': typeof ApiGenerateCreativeImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/compliance': typeof ComplianceRoute
  '/creative': typeof CreativeRoute
  '/creative-lab': typeof CreativeLabRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-creative-image': typeof ApiGenerateCreativeImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/campaigns'
    | '/compliance'
    | '/creative'
    | '/creative-lab'
    | '/sitemap.xml'
    | '/api/generate-creative-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/campaigns'
    | '/compliance'
    | '/creative'
    | '/creative-lab'
    | '/sitemap.xml'
    | '/api/generate-creative-image'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/campaigns'
    | '/compliance'
    | '/creative'
    | '/creative-lab'
    | '/sitemap.xml'
    | '/api/generate-creative-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CampaignsRoute: typeof CampaignsRoute
  ComplianceRoute: typeof ComplianceRoute
  CreativeRoute: typeof CreativeRoute
  CreativeLabRoute: typeof CreativeLabRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiGenerateCreativeImageRoute: typeof ApiGenerateCreativeImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative-lab': {
      id: '/creative-lab'
      path: '/creative-lab'
      fullPath: '/creative-lab'
      preLoaderRoute: typeof CreativeLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative': {
      id: '/creative'
      path: '/creative'
      fullPath: '/creative'
      preLoaderRoute: typeof CreativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-creative-image': {
      id: '/api/generate-creative-image'
      path: '/api/generate-creative-image'
      fullPath: '/api/generate-creative-image'
      preLoaderRoute: typeof ApiGenerateCreativeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CampaignsRoute: CampaignsRoute,
  ComplianceRoute: ComplianceRoute,
  CreativeRoute: CreativeRoute,
  CreativeLabRoute: CreativeLabRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiGenerateCreativeImageRoute: ApiGenerateCreativeImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
